apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: musman2003/flux-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_BASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REACT_APP_API_BASE
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: flux
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31730 # You can customize this port
  type: NodePort
