apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: flux
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM=   # base64 for 'postgres'
  DB_DATABASE: Zmx1eA==             # base64 for 'flux'
